import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/Toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // add what you actually use
  display: "swap",
});

export const metadata: Metadata = {
  title: "Feedsage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
